opinion_analysis:
  default:
    languages:
      - python3.12
    # cache:
    #   paths:
    #     - "~/.cache"
    steps:
      - run: mkdir -p python
        path: ./backend
      - run: python3 -m pip install -t python -r requirements.txt
        path: ./backend